### ISSUE TITLE
Branch feature/extra_contact_data from ign physics is used in tags.yaml but does not exist anymore.

### ISSUE THREAD

**Issue by wolfgangschwab** [robotology/gym-ignition#217]
In tags.yaml a special branch is used for ign-physics:

```
  ign-physics:
    type: git
    url: https://github.com/diegoferigo/ign-physics
    version: feature/extra_contact_data
```

It seems that this branch does not exist anymore.
