### ISSUE TITLE
Package a PyPI Wheel

### ISSUE THREAD

**Issue by diegoferigo** [robotology/gym-ignition#46]
In order to simplify the user installation and the deployment for training in cloud resources, having a PyPi package that contains a binary installation of gym-ignition would be highly beneficial.

In the beginning we can limit the support to manylinux x86_64, and slowly extend it by need.

The main problem is still how to install dependencies. For what concern ignition, most of the libraries can be installed from the official repository. The only exception is `ign-gazebo` since we still rely to a forked version. We should consider to polish the patch and open an upstream PR to add the additional components we need.

**Comment by diegoferigo** [comment]
In #55 I tried to implement an initial support of `bdist` packages, but due to the complexity of creating a `manylinux` release I limited the scope of that PR of only `sdist`.

Here below I report the Github Actions section to generate a `linux` release.

<details>
<summary>bdist section in pypi.yml</summary>

```yaml
  # ===================
  # BDIST_WHEEL PACKAGE
  # ===================

  bdist:
    name: bdist_wheel
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python_version:
          - 3.6
    runs-on: ${{ matrix.os }}
    container:
      image: diegoferigo/gym-ignition:ci
      env:
        CC: gcc
        CXX: g++
        PYTHON_VERSION: ${{ matrix.python_version }}

    steps:
      - uses: actions/checkout@master

      # Validate the last tag accordingly to PEP440
      # From https://stackoverflow.com/a/37972030/12150968
      - name: Validate Tag for PEP440 compliance
        run: |
          apt-get update
          apt-get install -y source-highlight
          last_tag="$(git describe --abbrev=0 --tags)"
          rel_regexp='^(\d+!)?(\d+)(\.\d+)+([\.\-\_])?((a(lpha)?|b(eta)?|c|r(c|ev)?|pre(view)?)\d*)?(\.?(post|dev)\d*)?$'
          echo ""
          echo $last_tag
          echo ""
          check-regexp ${rel_regexp} ${last_tag}
          match=$(check-regexp ${rel_regexp} ${last_tag} | grep matches | cut -d ' ' -f 5)
          test $match -eq 1 && true

      # The entrypoint is not called because it is overridden by GH Actions.
      # Even using the 'jobs.<job_id>.container.options' does not work because the
      # entrypoint of GH Actions overrides the one passed through YAML.
      - name: Execute entrypoint
        run: . /entrypoint.sh

      - name: Create package
        run: python setup.py bdist_wheel

      #
      # We should discuss about an extended support of linux distributions, switching to
      # a manylinux wheel.
      #
      # - https://opensource.com/article/19/2/manylinux-python-wheels
      # - https://thomastrapp.com/blog/building-a-pypi-package-for-a-modern-cpp-project/
      #
      # - name: Rename wheel
      #   run: |
      #     apt-get update
      #     apt-get install -y rename
      #     cd dist
      #     find -type f -name '*.whl' -exec rename.ul linux manylinux {} +

      - name: Install and test
        run: |
          cd dist
          pip install gym_ignition-*_x86_64.whl
          cd ../tests/python
          module_path=$(python -c "import gym_ignition ; print(gym_ignition.__path__[0])")
          module_path=$(echo $module_path | cut -d ' ' -f 1)
          export IGN_GAZEBO_SYSTEM_PLUGIN_PATH=${module_path}/plugins
          data_path=$(python -c "import gym_ignition_data ; print(gym_ignition_data.__path__[0])")
          export IGN_GAZEBO_RESOURCE_PATH=${data_path}:${data_path}/worlds
          pytest || true

      - name: Install twine
        if: github.event.action == 'published'
        run: pip install twine

      - name: Push to PyPI
        if: github.event.action == 'published'
        run: |
          env
          twine upload --verbose dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

```

</details>
